<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9thF371\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9thF371/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9thF371.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9thF371\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9thF371\App_KernelDevDebugContainer([
    'container.build_hash' => '9thF371',
    'container.build_id' => '39232726',
    'container.build_time' => 1703878598,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9thF371');
