<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMFbUl3x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMFbUl3x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMFbUl3x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMFbUl3x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMFbUl3x\App_KernelDevDebugContainer([
    'container.build_hash' => 'MFbUl3x',
    'container.build_id' => 'a45f9206',
    'container.build_time' => 1704288037,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMFbUl3x');
