<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'test' => [['name'], ['name' => 'world', '_controller' => 'App\\Controller\\HelloController::test'], ['name' => '[A-z0-9]{0,}'], [['variable', '/', '[A-z0-9]{0,}', 'name', true], ['text', '/test']], [['text', 'localhost']], ['https', 'http']],
    'index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/']], [], []],
];
